### PR TITLE
Workaround for Docker COPY bug

### LINKED ISSUE #176: Workaround for Docker bug with 7 consecutive COPY instructions
When a Dockerfile has 7 consecutive COPY instructions, the docker build fails on Xenit Jenkins with an error.

```
jenkins@29d24d8ba851:~/workspace/ithub_docker-alfresco_DOCKER-351/3legacy/5.1/enterprise-5.1.5/build/docker$ docker build . --no-cache
Sending build context to Docker daemon  70.66kB
Step 1/9 : FROM f4b9c4263b2d
 ---> f4b9c4263b2d
Step 2/9 : COPY share-config-custom.xml /docker-config/
 ---> 0dfe78211b72
Step 3/9 : COPY 91-init-share-customized.sh /docker-entrypoint.d/
 ---> da984df1598c
Step 4/9 : RUN chmod u+x /docker-entrypoint.d/91-init-share-customized.sh && mkdir -p "${CATALINA_HOME}/shared/classes/alfresco/web-extension/" && chown -R tomcat:tomcat "${CATALINA_HOME}/shared/classes/alfresco/web-extension/"
 ---> Running in 9ec3a8a213e0
Removing intermediate container 9ec3a8a213e0
 ---> 9a013ed3db7c
Step 5/9 : ENV ALFRESCO_FLAVOR=enterprise
 ---> Running in 8521bda69aa9
Removing intermediate container 8521bda69aa9
 ---> 20af8bcd6795
Step 6/9 : ENV ALFRESCO_VERSION=5.1.5
 ---> Running in c017a8c6b777
Removing intermediate container c017a8c6b777
 ---> 68ad2cb90fa0
Step 7/9 : COPY copyFile/1/ copyFile/2/ copyFile/3/ copyFile/4/ copyFile/5/ copyFile/6/ /usr/local/tomcat/webapps/alfresco/
 ---> c6bb7c8bf5a3
Step 8/9 : COPY copyFile/7/ /usr/local/tomcat/webapps/share/
failed to export image: failed to create image: failed to get layer sha256:2b0f077f9e2402cd5225514da3d0e7d838bb33f01e452788bfbe571110eb03d9: layer does not exist
```

Adding a simple RUN instruction inbetween avoids this problem:

```
jenkins@29d24d8ba851:~/workspace/ithub_docker-alfresco_DOCKER-351/3legacy/5.1/enterprise-5.1.5/build/docker$ docker build . --no-cache
Sending build context to Docker daemon  78.85kB
Step 1/15 : FROM f4b9c4263b2d
 ---> f4b9c4263b2d
Step 2/15 : COPY share-config-custom.xml /docker-config/
 ---> d4cd30d19fbe
Step 3/15 : COPY 91-init-share-customized.sh /docker-entrypoint.d/
 ---> 6dca5b18eaed
Step 4/15 : RUN chmod u+x /docker-entrypoint.d/91-init-share-customized.sh && mkdir -p "${CATALINA_HOME}/shared/classes/alfresco/web-extension/" && chown -R tomcat:tomcat "${CATALINA_HOME}/shared/classes/alfresco/web-extension/"
 ---> Running in f846e2398517
Removing intermediate container f846e2398517
 ---> c8ed9296cc5f
Step 5/15 : ENV ALFRESCO_FLAVOR=enterprise
 ---> Running in 4d34a0413cd4
Removing intermediate container 4d34a0413cd4
 ---> 1ba27f4a6b23
Step 6/15 : ENV ALFRESCO_VERSION=5.1.5
 ---> Running in b0622e474210
Removing intermediate container b0622e474210
 ---> 3c57d926c3ed
Step 7/15 : COPY copyFile/1/ /usr/local/tomcat/webapps/alfresco/
 ---> bb6f8e8f7f45
Step 8/15 : COPY copyFile/2/ /usr/local/tomcat/webapps/alfresco/
 ---> 0b6319de874f
Step 9/15 : COPY copyFile/3/ /usr/local/tomcat/webapps/alfresco/
 ---> 2e222ca2bba3
Step 10/15 : COPY copyFile/4/ /usr/local/tomcat/webapps/alfresco/
 ---> 52158f685a67
Step 11/15 : COPY copyFile/5/ /usr/local/tomcat/webapps/alfresco/
 ---> 113b798d4539
Step 12/15 : COPY copyFile/6/ /usr/local/tomcat/webapps/alfresco/
 ---> cd1001ddae1a
Step 13/15 : RUN true
 ---> Running in da8b12b183b0
Removing intermediate container da8b12b183b0
 ---> 623a9c747787
Step 14/15 : COPY copyFile/7/ /usr/local/tomcat/webapps/share/
 ---> e5487c8e7b6e
Step 15/15 : COPY copyFile/8/ copyFile/9/ copyFile/10/ copyFile/11/ /usr/local/tomcat/webapps/share/
 ---> d187f5fe7c15
Successfully built d187f5fe7c15
```

Consolidation of COPY commands was introduced to improve the build speed of Docker images, but in some cases may now prevent applying a monkey-patch by inserting `RUN true` instructions between `COPY` instructions (because they are rolled into one)

To get the best of both worlds (performance improvements where possible, slower builds but without errors when necessary), we will gate the functionality of adding dummy instructions behind a Gradle property that can be configured in `~/.gradle/gradle.properties` on machines where this issue occurs.

### PR DESCRIPTION
**Pull request by vierbergenlars**
Fixes #176 

Integration test depends on #175, so this PR should be rebased after that one is merged.

### CODE REVIEW

File: src/main/java/eu/xenit/gradle/docker/tasks/internal/WorkaroundDockerdConsecutiveCopyBugAction.java [hunk 1]
```diff
@@ -0,0 +1,153 @@
...
+import org.gradle.api.Task;
+import org.gradle.api.logging.Logger;
+import org.gradle.api.logging.Logging;
+
+@NonNullApi
+public class WorkaroundDockerdConsecutiveCopyBugAction implements Action<Task> {
+
+    private static final Logger LOGGER = Logging.getLogger(WorkaroundDockerdConsecutiveCopyBugAction.class);
+    public static final String FEATURE_FLAG = "eu.xenit.docker.flags.workaround-dockerd-consecutive-copy-bug";
+    private static final int MAX_CONSECUTIVE_COPIES = 6;
```
Comment (kerkhofsd) [inline src/main/java/eu/xenit/gradle/docker/tasks/internal/WorkaroundDockerdConsecutiveCopyBugAction.java:21]: Should we make this configurable as well? Is it somehow possible this changes on different docker versions / hosts?

**Review by kerkhofsd — APPROVED** [review]

File: src/main/java/eu/xenit/gradle/docker/tasks/internal/WorkaroundDockerdConsecutiveCopyBugAction.java (hunk 1 above)
Comment (vierbergenlars) [reply src/main/java/eu/xenit/gradle/docker/tasks/internal/WorkaroundDockerdConsecutiveCopyBugAction.java:21]: Good point. An extra property does not really cost much anyways and saves us from having to release a new version when we need to tweak it.
